In [1]:
num =1

In [2]:
print(num)

1


In [4]:
num1 =1
num2 = 2

In [5]:
print(num1)
print(num2)

1
2


In [6]:
import numpy as np

In [8]:
arr1 = np.array([1,2,3,4])

In [9]:
arr1

array([1, 2, 3, 4])

In [10]:
arr1.shape

(4,)

In [12]:
arr2 = np.array([[1,2],[3,5]])

In [13]:
arr2.shape

(2, 2)

In [15]:
arr3 = np.array([1.1,2,3.4],dtype = np.float32)

In [16]:
arr3

array([1.1, 2. , 3.4], dtype=float32)

In [19]:
arr4 = np.array([1,2.3,3.4,6],dtype = np.int32)

In [20]:
arr4

array([1, 2, 3, 6])

In [26]:
arr5 = arr4.reshape(2,2)

In [27]:
arr5

array([[1, 2],
       [3, 6]])

In [28]:
arr6 = arr5.reshape(4)

In [29]:
arr6

array([1, 2, 3, 6])

In [30]:
arr7  = np.zeros(5)

In [31]:
arr7

array([0., 0., 0., 0., 0.])

In [32]:
arr8 = np.ones(1)

In [33]:
arr8

array([1.])

In [34]:
np.ones(4)

array([1., 1., 1., 1.])

In [35]:
np.full(5,4)

array([4, 4, 4, 4, 4])

In [36]:
np.full((5,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [38]:
arr9 = np.array([[1,2,3,4],[5,6,7,8]])

In [39]:
arr9

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
arr9.sum()

36

In [42]:
arr9.sum(axis = 1)

array([10, 26])

In [43]:
arr9.sum(axis = 0)

array([ 6,  8, 10, 12])

In [44]:
arr9.mean(axis = 1)

array([2.5, 6.5])